###############################################################################
### Figure 7 - Extinction as a function of system size ########################
###############################################################################

# Nick Lowery and Tristan Ursell
# 2018
# 
# This script generates Figure 7 from our preprint:
# Structured environments fundamentally alter dynamics and stability of ecological communities
# https://www.biorxiv.org/content/early/2018/07/10/366559
# 
# The script reads in metadata files, as generated by the LV_competition_function.m 
# function.  Code used to generate the cleaned data tables is included below but 
# commented out.  This script calculates the frequency of extinction in the three 
# species simulations, as a function of the system size (L), keeping the environmental 
# structure (i.e. R and dx) constant.

###############################################################################

# library(R.matlab)
library(tidyverse)
library(cowplot)

# # Read in data
# ss.metadata.raw <- list.files("3sp_sys_size", pattern = ".mat", full.names = T) %>%
#   lapply(., readMat)
# 
# pillar.weights <- read_csv("filt_all_weights_L.csv", col_names = c("L","R","dx","pillar.weight")) %>%
#   mutate(dx = round(dx*R))
# 
# 
# ### extinction over short time scales (1000 doubling times)
# 
# # organize list into tbl
# ss.metadata.temp <- ss.metadata.raw %>% {
#   tibble(
#     L = map_dbl(., "L"),
#     N = map_dbl(., "N"),
#     P = map_dbl(., "P"),
#     pillars = map_dbl(., "pillarq"),
#     R = map_dbl(., "R"), 
#     dx = map_dbl(., "dx"),
#     rep = map_dbl(., "rep"),
#     data = map(., `[`, c("meanA.out", "meanB.out", "meanC.out")) %>% map(data.frame)
#   )
# } %>%
#   unnest() %>%
#   rename(A = meanA.out, B = meanB.out, C = meanC.out) %>%
#   mutate(t.step = rep(seq(0.2,1000,by=0.2), length(ss.metadata.raw)))
# 
# # join with pillar weight table and calculate extionction frequency
# ss.metadata <- left_join(ss.metadata.temp, pillar.weights) %>%
#   mutate(pillar.weight = ifelse(R == 0 & dx == 0, L^2, pillar.weight))
# 
# # write cleaned data file
# write_csv(ss.metadata, "system_size_short_time_cleaned_data.csv")
ss.metadata <- read_csv("system_size_short_time_cleaned_data.csv", col_types = 'dddiiiiddddd')

ss.summary <- ss.metadata %>%
  mutate(extinct = ifelse(A <= ((2*R)^2 - pi*R^2)/4/pillar.weight | 
                          B <= ((2*R)^2 - pi*R^2)/4/pillar.weight | 
                          C <= ((2*R)^2 - pi*R^2)/4/pillar.weight, 1, 0),
         # convert L to dimensionless natural length (nl) scale
         L.nl = round(L/sqrt(15), digits = 2)) %>%
  group_by(L.nl, N, P, pillars, R, dx, rep) %>%
  summarise(extinction = max(extinct),
            t.extinct = ifelse(max(extinct), t.step[which.max(extinct)], NA)) 

ss.propext <- ss.summary %>%
  group_by(L.nl, N) %>%
  summarise(prop.extinct = sum(extinction)/n())


### extinction over long time scales

# # Read in data
# long.metadata.raw <- list.files("3sp_long", pattern = ".mat", full.names = T) %>%
#   lapply(., readMat)
# 
# # get things organized
# long.metadata.temp <- long.metadata.raw %>% {
#   tibble(
#     L = map_dbl(., "L"),
#     N = map_dbl(., "N"),
#     P = map_dbl(., "P"),
#     pillars = map_dbl(., "pillarq"),
#     R = map_dbl(., "R"), 
#     dx = map_dbl(., "dx"),
#     rep = map_dbl(., "rep"),
#     data = map(., `[`, c("meanA.out", "meanB.out", "meanC.out")) %>% map(data.frame)
#   )
# } %>%
#   unnest() %>%
#   rename(A = meanA.out, B = meanB.out, C = meanC.out) %>%
#   mutate(t.step = rep(seq(0.2,10000,by=0.2), length(long.metadata.raw)))
# 
# long.metadata <- left_join(long.metadata.temp, pillar.weights) %>%
#   mutate(pillar.weight = ifelse(R == 0 & dx == 0, L^2, pillar.weight))
# 
# # write cleaned data
# write_csv(long.metadata, "system_size_long_time_cleaned_data.csv")
long.metadata <- read_csv("system_size_long_time_cleaned_data.csv", col_types = 'dddiiiiddddd')

long.summary <- long.metadata %>%
  mutate(extinct = ifelse(A <= ((2*R)^2 - pi*R^2)/4/pillar.weight | 
                          B <= ((2*R)^2 - pi*R^2)/4/pillar.weight | 
                          C <= ((2*R)^2 - pi*R^2)/4/pillar.weight, 1, 0),
         L.nl = round(L/sqrt(15), digits = 2)) %>%
  group_by(L.nl, N, P, pillars, R, dx, rep) %>%
  summarise(extinction = max(extinct),
            t.extinct = ifelse(max(extinct), t.step[which.max(extinct)], NA))

long.propext <- long.summary %>%
  group_by(L.nl, N) %>%
  summarise(prop.extinct = sum(extinction)/n())


# combine data for plotting
sl.summary <- rbind(ss.summary, long.summary)
sl.propext <- rbind(ss.propext, long.propext)

# time to extinction as a function of system size
textinct <- ggplot(subset(sl.summary, L.nl > min(L.nl)), aes(x = L.nl, y = t.extinct, color = as.factor(N))) +
  geom_point(size=3) +
  scale_color_manual(values = c("black","red")) +
  scale_x_continuous(limits = c(0,1500), breaks = c(0,500,1000,1500)) +
  labs(x = expression(paste("system size ( L / ", lambda, ")")), 
       y = "time to extinction (doubling times)") +
  guides(color = F)

logtextinct <- ggplot(subset(sl.summary, L.nl > min(L.nl)), aes(x = L.nl, y = t.extinct, color = as.factor(N))) +
  geom_smooth(aes(group = 1), method = "lm", se = F, size = 1.25, color = "grey") +
  geom_point(size=3) +
  scale_color_manual(values = c("black","red"), labels = c(1000, 10000)) +
  scale_y_log10(limits = c(10,10000), breaks = c(10, 100, 1000, 10000)) +
  labs(x = expression(paste("system size ( L / ", lambda, ")")), 
       y = "time to extinction (doubling times)", 
       color = paste("Simulation Length", "(doubling times)", sep = "\n"))  +
  theme(legend.position = c(0.45, 0.15))
  
# frequency of extinction as a function of system size
propext <- ggplot(subset(sl.propext, L.nl > min(L.nl)), aes(x = L.nl, y = prop.extinct, color = as.factor(N))) +
  stat_smooth(data = ss.propext, aes(x = L.nl, y = prop.extinct), se = F, size = 1.25, alpha = 0.5, color = "grey",
              method = "glm", method.args = list(family = "binomial")) +
  geom_point(size = 3) +
  scale_color_manual(values = c("black","red")) +
  labs(x = expression(paste("system size ( L / ", lambda, ")")), 
       y = "extinction frequency") +
  guides(color = F)

# final figure
plot_grid(logtextinct, propext, nrow = 1, labels = "AUTO", label_size = 24)

