###############################################################################
### Figure S13 - Randomized pillar lattices ###################################
###############################################################################

# Nick Lowery and Tristan Ursell
# 2018
# 
# This script generates Figure S13 from our preprint:
# Structured environments fundamentally alter dynamics and stability of ecological communities
# https://www.biorxiv.org/content/early/2018/07/10/366559
# 
# The script reads in metadata files, as generated by the 
# LV_competition_function_jitter_grid.m function.  Code used to generate the 
# cleaned data tables is included below but commented out.  This script calculates
# the frequency of extinction in the three species simulations, as a function 
# of the degree of random perturbation imposesd on the pillar lattice.

###############################################################################

# library(R.matlab)
library(tidyverse)
library(cowplot)

# # read in data
# jitt.metadata.raw <- list.files("3sp_jitter", pattern = ".mat", full.names = T) %>%
#   lapply(., readMat)
# 
# jitt.controls.raw <- list.files("3sp_jitter_controls", pattern = ".mat", full.names = T) %>%
#   lapply(., readMat)
# 
# jitt.all.raw <- c(jitt.metadata.raw, jitt.controls.raw)
# 
# # organize data into tbl
# jitt.metadata <- jitt.all.raw %>% {
#   tibble(
#     L = map_dbl(., "L"),
#     N = map_dbl(., "N"),
#     P = map_dbl(., "P"),
#     pillars = map_dbl(., "pillarq"),
#     R = map_dbl(., "R"),
#     dx = map_dbl(., "dx"),
#     rep = map_dbl(., "rep"),
#     R.var = map_dbl(., "jitt.R"),
#     dx.var = map_dbl(., "jitt.dx"),
#     grid.id = map_dbl(., "jitt.num"),
#     pillar.weight = map_dbl(., "filt.all.weight"),
#     data = map(., `[`, c("meanA.out", "meanB.out", "meanC.out")) %>% map(data.frame)
#   )
#   } %>%
#   mutate(data = map(data, ~mutate(.x, t.step = seq(0.2, 1000, by = 0.2)))) %>%
#   unnest() %>%
#   rename(A = meanA.out, B = meanB.out, C = meanC.out) %>%
#   mutate(extinct = ifelse(A <= ((2*(R+R.var))^2 - pi*(R+R.var)^2)/4/pillar.weight |  
#                           B <= ((2*(R+R.var))^2 - pi*(R+R.var)^2)/4/pillar.weight |
#                           C <= ((2*(R+R.var))^2 - pi*(R+R.var)^2)/4/pillar.weight , 1, 0),
#          # convert to natural length scale units
#          R = round(R/sqrt(15), digits = 2),  
#          dx = round(dx/sqrt(15), digits = 2),
#          # convert to variance (sd) of uniform distribution
#          R.sd = round(sqrt(1/3*R.var^2/sqrt(15)), digits = 3), 
#          dx.sd = round(sqrt(1/12*dx.var^2/sqrt(15)), digits = 3))
# 
# jitt.summary <- jitt.metadata %>%
#   group_by(R, dx, R.sd, dx.sd, grid.id, rep) %>%
#   summarise(t.extinct = ifelse(max(extinct), t.step[which.max(extinct)], NA)) 
#
# # write cleaned data table
# write_csv(jitt.summary, "jittered_grid_cleaned_data.csv")
jitt.summary <- read_csv("jittered_grid_cleaned_data.csv")

# plot time to extinction as a function of grid perturbation
top.row <- ggplot(filter(jitt.summary, R.sd == 0), aes(x = as.factor(R), y = t.extinct)) +
  geom_jitter(size = 2, alpha = 0.8, width = 0.2, height = 0) +
  facet_wrap(~ dx.sd, nrow = 1, labeller = label_bquote(.(dx.sd)*R)) +
  panel_border() +
  labs(title = expression(paste(Delta, "x standard deviation", sep="")),
       x = expression(paste("pillar radius (R / ", lambda, ")")), 
       y = paste("time to extinction", "(doubling times)", sep = "\n"))
  
bottom.row <- ggplot(filter(jitt.summary, dx.sd == 0), aes(x = as.factor(R), y = t.extinct)) +
  geom_jitter(size = 2, alpha = 0.8, width = 0.2, height = 0) +
  facet_wrap(~ R.sd, nrow = 1, labeller = label_bquote(.(R.sd)*R)) +
  panel_border() +
  labs(title = "R standard deviation",
       x = expression(paste("mean pillar radius (R / ", lambda, ")")), 
       y = paste("time to extinction", "(doubling times)", sep = "\n")) 

plot_grid(top.row, bottom.row, nrow = 2, labels = "AUTO", label_size = 24)


# extinction frequencies
jitt.summary %>%
  group_by(R, dx, R.sd, dx.sd) %>%
  summarise(ext.freq = sum(is.finite(t.extinct))) %>%
  print(n = Inf)

